
datasets:
  egoirgbench: # name of the dataset builder
    # dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images 

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: /mnt/nvme1/suyuejiao/Final_rgbd_dataset/ANNEXE/dataset_split/new_new_train/ # must be absolute path
        val:
          storage: /mnt/nvme1/suyuejiao/Final_rgbd_dataset/ANNEXE/dataset_split/new_new_val/
        test:
          storage: /mnt/nvme1/suyuejiao/Final_rgbd_dataset/ANNEXE/dataset_split/new_new_test/
      images:
        storage: /mnt/nvme1/suyuejiao/Final_rgbd_dataset/ANNEXE/RGB/
        
