
datasets:
  egoirgbench: # name of the dataset builder
    # dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images 

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: path/to/train_set/ # must be absolute path
        val:
          storage: path/to/val_set
        test:
          storage: path/to/test_set
      images:
        storage: path/to/RGB_folder
        

